/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package popdig;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
		new PopiangDigital().proc(args);
        //System.out.println(new App().getGreeting());
    }
}
